version: 0.2

phases:
  install:
    commands:
      - echo "No Install required"
  pre_build:
    commands:
      - pip install pandas requests
      - npm install -g aws-cdk
      - cdk --version    
  build:
    commands:
      - echo "[+] Installing dependencies...."
      - echo "Starting SAM packaging `date` in `pwd`"
      - sam package --template-file template.yml --output-template-file packaged-template.yml
      - sam deploy --template-file packaged-template.yml --stack-name sammlops02 --capabilities CAPABILITY_IAM 
  post_build:
    commands:
      - echo "SAM packaging completed on `date`"
artifacts:
  files:
    - packaged-template.yml



