version: 0.2

phases:
  install:
    commands:
      - echo "[+] Scanning for security vulnerability within dependencies"
      # - pipenv check (if pipenv is installed and a Pipfile is in place)
      # - Alternatively: https://www.owasp.org/index.php/OWASP_Dependency_Check
  pre_build:
    commands:
      - pip install pandas requests cdk
      - npm install -g aws-cdk
      - cdk --version    
  build:
    commands:
      - echo "[+] Installing dependencies...."
      - echo "Starting SAM packaging `date` in `pwd`"
      - echo "aws cloudformation package --template-file template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file packaged.yaml"
  post_build:
    commands:
      - echo "SAM packaging completed on `date`"



